# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='img', upload_to=b''),
            preserve_default=False,
        ),
    ]
